<a href="https://colab.research.google.com/github/AKHILESH-create/AIML-Concepts/blob/main/AI_Training1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LIST

In [ ]:
l1 = [1,2,3,4,5]
print(l1)

[1, 2, 3, 4, 5]


In [ ]:
l1 = []
l1.append(1)
l1.append(2)
l1.append(3)
l1.append(4)
l1.append(5)
print(l1)

[1, 2, 3, 4, 5]


In [ ]:
#extend
a = [1,2,3,4]
b = [3,4,5]
a.extend(b)
print(a)

[1, 2, 3, 4, 3, 4, 5]


TUPLE

In [ ]:
#tuple
t = (10,20,30)
print(type(t))

<class 'tuple'>


In [ ]:
print(t[1])

20


In [ ]:
t1=(20,30,40)
print(t1)
print("-----------")
print(t)

(20, 30, 40)
-----------
(10, 20, 30)


In [ ]:
t2= t+t1
print(t2)
x=t2.count(20)
print(x)

(10, 20, 30, 20, 30, 40)
2


SET

In [ ]:
s={1,2,-3,-4,5,10,20}
print(type(s))
print(len(s))


<class 'set'>
7


In [ ]:
#adding elements in set
s.add("Python")
print(s)
print(len(s))

{1, 2, 20, 5, 10, -4, -3, 'Python'}
8


In [ ]:
s.add("ML")
print(s)
print(len(s))


{1, 2, 5, 10, 20, 'ML', -4, -3, 'Python'}
9


In [ ]:
s.discard("Python")
print(s)

{1, 2, 5, 10, 20, 'ML', -4, -3}


In [ ]:
s1={2,4,6}
s2={4,8,10}
print(s1.union(s2))
print(s1)

{2, 4, 6, 8, 10}
{2, 4, 6}


DICTIONARY

In [ ]:
dic1={
      "Employee": "Prashant",
      "Id": "800",
      "Salary": 85000
}
print(dic1)
print(type(dic1))

{'Employee': 'Prashant', 'Id': '800', 'Salary': 85000}
<class 'dict'>


In [ ]:
print(dic1["Employee"])


Prashant


In [ ]:
print(dic1["Salary"])

85000


In [ ]:
dic1={
      "Employee": "Prashant",
      "Id": "800",
      "Salary": 85000, "Salary":95000
}
print(dic1)
print(type(dic1))

{'Employee': 'Prashant', 'Id': '800', 'Salary': 95000}
<class 'dict'>


In [ ]:
dic1["Age"]=35
print(dic1)

{'Employee': 'Prashant', 'Id': '800', 'Salary': 95000, 'Age': 35}


In [ ]:
#update
dic1.update({"Age":37})
print(dic1)

{'Employee': 'Prashant', 'Id': '800', 'Salary': 95000, 'Age': 37}


In [ ]:
dic1.update({"Mobile": 3888888888888})
print(dic1)

{'Employee': 'Prashant', 'Salary': 95000, 'Mobile': 3888888888888}


POP

In [ ]:
dic1.pop("Id", None)
print(dic1)

{'Employee': 'Prashant', 'Salary': 95000, 'Mobile': 3888888888888}


In [ ]:
dic1 = {'Employee': 'Prashant', 'Salary': 95000, 'Mobile': 3888888888888} # Re-initialize dic1
dic1.popitem()
print(dic1)

{'Employee': 'Prashant', 'Salary': 95000}


ML ................

NUMPY

In [ ]:
import numpy as np


In [ ]:
a1= np.array([1,2,3,4,5])
print(a1)
l1=['Python',10,5,5]
a2=np.array(l1)
print(a2)

[1 2 3 4 5]
['Python' '10' '5' '5']


In [ ]:
a2=np.array([[1,2,3],[5,6,7]])
print(a2)
a2.ndim

[[1 2 3]
 [5 6 7]]


2

In [ ]:
#arrange
a=np.arange(20)
print(a)
a=np.arange(1,20,dtype='float')
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19.]
